In [1]:
# Retail Sales Data Warehouse Project
# Step 1: Import required libraries

import pandas as pd
import sqlite3
from datetime import datetime

print("Data Warehouse Project Started Successfully!")

Data Warehouse Project Started Successfully!

In [2]:
# Step 2: Create Source Sales Data

sales_data = {
    'Transaction_ID': ['T001', 'T002', 'T003', 'T004', 'T005',
                       'T006', 'T007', 'T008', 'T009', 'T010'],
    'Date': ['2026-07-01', '2026-07-02', '2026-07-03', '2026-07-04', '2026-07-05',
             '2026-07-06', '2026-07-07', '2026-07-08', '2026-07-09', '2026-07-10'],
    'Customer_ID': ['C001', 'C002', 'C003', 'C001', 'C004',
                    'C005', 'C002', 'C003', 'C004', 'C005'],
    'Customer_Name': ['Kamal', 'Nimali', 'Saman', 'Kamal', 'Amali',
                      'Nuwan', 'Nimali', 'Saman', 'Amali', 'Nuwan'],
    'City': ['Colombo', 'Kandy', 'Galle', 'Colombo', 'Kurunegala',
             'Colombo', 'Kandy', 'Galle', 'Kurunegala', 'Colombo'],
    'Product_ID': ['P001', 'P002', 'P003', 'P002', 'P001',
                   'P004', 'P003', 'P001', 'P004', 'P002'],
    'Product_Name': ['Laptop', 'Mouse', 'Keyboard', 'Mouse', 'Laptop',
                     'Monitor', 'Keyboard', 'Laptop', 'Monitor', 'Mouse'],
    'Category': ['Electronics', 'Accessories', 'Accessories', 'Accessories',
                 'Electronics', 'Electronics', 'Accessories', 'Electronics',
                 'Electronics', 'Accessories'],
    'Store_ID': ['S001', 'S001', 'S002', 'S001', 'S002',
                 'S001', 'S002', 'S002', 'S001', 'S002'],
    'Quantity': [1, 2, 1, 3, 1, 1, 2, 1, 1, 4],
    'Unit_Price': [250000, 3500, 7500, 3500, 250000,
                   65000, 7500, 250000, 65000, 3500],
    'Discount': [10000, 500, 0, 500, 15000, 5000, 1000, 10000, 3000, 1000]
}

source_sales = pd.DataFrame(sales_data)

source_sales

,Transaction_ID,Date,Customer_ID,Customer_Name,City,Product_ID,Product_Name,Category,Store_ID,Quantity,Unit_Price,Discount
0,T001,2026-07-01,C001,Kamal,Colombo,P001,Laptop,Electronics,S001,1,250000,10000
1,T002,2026-07-02,C002,Nimali,Kandy,P002,Mouse,Accessories,S001,2,3500,500
2,T003,2026-07-03,C003,Saman,Galle,P003,Keyboard,Accessories,S002,1,7500,0
3,T004,2026-07-04,C001,Kamal,Colombo,P002,Mouse,Accessories,S001,3,3500,500
4,T005,2026-07-05,C004,Amali,Kurunegala,P001,Laptop,Electronics,S002,1,250000,15000
5,T006,2026-07-06,C005,Nuwan,Colombo,P004,Monitor,Electronics,S001,1,65000,5000
6,T007,2026-07-07,C002,Nimali,Kandy,P003,Keyboard,Accessories,S002,2,7500,1000
7,T008,2026-07-08,C003,Saman,Galle,P001,Laptop,Electronics,S002,1,250000,10000
8,T009,2026-07-09,C004,Amali,Kurunegala,P004,Monitor,Electronics,S001,1,65000,3000
9,T010,2026-07-10,C005,Nuwan,Colombo,P002,Mouse,Accessories,S002,4,3500,1000

In [3]:
# Step 3: Create Staging Layer

staging_sales = source_sales.copy()

# Convert Date column to proper date format
staging_sales['Date'] = pd.to_datetime(staging_sales['Date'])

# Remove duplicate records
staging_sales = staging_sales.drop_duplicates()

# Check for missing values
print("Missing Values:")
print(staging_sales.isnull().sum())

print("\nStaging Data:")
display(staging_sales)

Missing Values:
Transaction_ID    0
Date              0
Customer_ID       0
Customer_Name     0
City              0
Product_ID        0
Product_Name      0
Category          0
Store_ID          0
Quantity          0
Unit_Price        0
Discount          0
dtype: int64

Staging Data:

,Transaction_ID,Date,Customer_ID,Customer_Name,City,Product_ID,Product_Name,Category,Store_ID,Quantity,Unit_Price,Discount
0,T001,2026-07-01,C001,Kamal,Colombo,P001,Laptop,Electronics,S001,1,250000,10000
1,T002,2026-07-02,C002,Nimali,Kandy,P002,Mouse,Accessories,S001,2,3500,500
2,T003,2026-07-03,C003,Saman,Galle,P003,Keyboard,Accessories,S002,1,7500,0
3,T004,2026-07-04,C001,Kamal,Colombo,P002,Mouse,Accessories,S001,3,3500,500
4,T005,2026-07-05,C004,Amali,Kurunegala,P001,Laptop,Electronics,S002,1,250000,15000
5,T006,2026-07-06,C005,Nuwan,Colombo,P004,Monitor,Electronics,S001,1,65000,5000
6,T007,2026-07-07,C002,Nimali,Kandy,P003,Keyboard,Accessories,S002,2,7500,1000
7,T008,2026-07-08,C003,Saman,Galle,P001,Laptop,Electronics,S002,1,250000,10000
8,T009,2026-07-09,C004,Amali,Kurunegala,P004,Monitor,Electronics,S001,1,65000,3000
9,T010,2026-07-10,C005,Nuwan,Colombo,P002,Mouse,Accessories,S002,4,3500,1000

In [4]:
# Step 4: Transform Data and Calculate Measures

# Calculate Gross Sales
staging_sales['Gross_Sales'] = (
    staging_sales['Quantity'] * staging_sales['Unit_Price']
)

# Calculate Net Sales after discount
staging_sales['Net_Sales'] = (
    staging_sales['Gross_Sales'] - staging_sales['Discount']
)

print("Transformation Completed Successfully!")

display(
    staging_sales[
        ['Transaction_ID', 'Product_Name', 'Quantity',
         'Unit_Price', 'Discount', 'Gross_Sales', 'Net_Sales']
    ]
)

Transformation Completed Successfully!

,Transaction_ID,Product_Name,Quantity,Unit_Price,Discount,Gross_Sales,Net_Sales
0,T001,Laptop,1,250000,10000,250000,240000
1,T002,Mouse,2,3500,500,7000,6500
2,T003,Keyboard,1,7500,0,7500,7500
3,T004,Mouse,3,3500,500,10500,10000
4,T005,Laptop,1,250000,15000,250000,235000
5,T006,Monitor,1,65000,5000,65000,60000
6,T007,Keyboard,2,7500,1000,15000,14000
7,T008,Laptop,1,250000,10000,250000,240000
8,T009,Monitor,1,65000,3000,65000,62000
9,T010,Mouse,4,3500,1000,14000,13000

In [5]:
# Step 5: Create Dimension Tables with Surrogate Keys

# Customer Dimension
dim_customer = staging_sales[
    ['Customer_ID', 'Customer_Name', 'City']
].drop_duplicates().reset_index(drop=True)

dim_customer.insert(0, 'Customer_SK', range(1, len(dim_customer) + 1))


# Product Dimension
dim_product = staging_sales[
    ['Product_ID', 'Product_Name', 'Category']
].drop_duplicates().reset_index(drop=True)

dim_product.insert(0, 'Product_SK', range(1, len(dim_product) + 1))


# Store Dimension
dim_store = pd.DataFrame({
    'Store_ID': ['S001', 'S002'],
    'Store_Name': ['Colombo Store', 'Kandy Store']
})

dim_store.insert(0, 'Store_SK', range(1, len(dim_store) + 1))


# Date Dimension
dim_date = pd.DataFrame({
    'Date': staging_sales['Date'].drop_duplicates().sort_values()
}).reset_index(drop=True)

dim_date['Day'] = dim_date['Date'].dt.day
dim_date['Month'] = dim_date['Date'].dt.month
dim_date['Year'] = dim_date['Date'].dt.year
dim_date.insert(0, 'Date_SK', range(1, len(dim_date) + 1))


print("CUSTOMER DIMENSION")
display(dim_customer)

print("PRODUCT DIMENSION")
display(dim_product)

print("STORE DIMENSION")
display(dim_store)

print("DATE DIMENSION")
display(dim_date)

CUSTOMER DIMENSION

   Customer_SK Customer_ID Customer_Name        City
0            1        C001         Kamal     Colombo
1            2        C002        Nimali       Kandy
2            3        C003         Saman       Galle
3            4        C004         Amali  Kurunegala
4            5        C005         Nuwan     Colombo

PRODUCT DIMENSION

   Product_SK Product_ID Product_Name     Category
0           1       P001       Laptop  Electronics
1           2       P002        Mouse  Accessories
2           3       P003     Keyboard  Accessories
3           4       P004      Monitor  Electronics

STORE DIMENSION

   Store_SK Store_ID     Store_Name
0         1     S001  Colombo Store
1         2     S002    Kandy Store

DATE DIMENSION

   Date_SK       Date  Day  Month  Year
0        1 2026-07-01    1      7  2026
1        2 2026-07-02    2      7  2026
2        3 2026-07-03    3      7  2026
3        4 2026-07-04    4      7  2026
4        5 2026-07-05    5      7  2026
5        6 2026-07-06    6      7  2026
6        7 2026-07-07    7      7  2026
7        8 2026-07-08    8      7  2026
8        9 2026-07-09    9      7  2026
9       10 2026-07-10   10      7  2026

In [6]:
# Step 6: Create Fact Sales Table

fact_sales = staging_sales.copy()

# Add Customer_SK
fact_sales = fact_sales.merge(
    dim_customer[['Customer_SK', 'Customer_ID', 'Customer_Name', 'City']],
    on=['Customer_ID', 'Customer_Name', 'City'],
    how='left'
)

# Add Product_SK
fact_sales = fact_sales.merge(
    dim_product[['Product_SK', 'Product_ID', 'Product_Name', 'Category']],
    on=['Product_ID', 'Product_Name', 'Category'],
    how='left'
)

# Add Store_SK
fact_sales = fact_sales.merge(
    dim_store[['Store_SK', 'Store_ID']],
    on='Store_ID',
    how='left'
)

# Add Date_SK
fact_sales = fact_sales.merge(
    dim_date[['Date_SK', 'Date']],
    on='Date',
    how='left'
)

# Keep only Fact Table columns
fact_sales = fact_sales[
    [
        'Transaction_ID',
        'Date_SK',
        'Customer_SK',
        'Product_SK',
        'Store_SK',
        'Quantity',
        'Unit_Price',
        'Discount',
        'Gross_Sales',
        'Net_Sales'
    ]
]

print("FACT SALES TABLE")
display(fact_sales)

FACT SALES TABLE

,Transaction_ID,Date_SK,Customer_SK,Product_SK,Store_SK,Quantity,Unit_Price,Discount,Gross_Sales,Net_Sales
0,T001,1,1,1,1,1,250000,10000,250000,240000
1,T002,2,2,2,1,2,3500,500,7000,6500
2,T003,3,3,3,2,1,7500,0,7500,7500
3,T004,4,1,2,1,3,3500,500,10500,10000
4,T005,5,4,1,2,1,250000,15000,250000,235000
5,T006,6,5,4,1,1,65000,5000,65000,60000
6,T007,7,2,3,2,2,7500,1000,15000,14000
7,T008,8,3,1,2,1,250000,10000,250000,240000
8,T009,9,4,4,1,1,65000,3000,65000,62000
9,T010,10,5,2,2,4,3500,1000,14000,13000

In [7]:
# Step 7: Create SQLite Data Warehouse Database

# Create database connection
conn = sqlite3.connect('retail_data_warehouse.db')

# Load Dimension Tables
dim_customer.to_sql('Dim_Customer', conn, if_exists='replace', index=False)
dim_product.to_sql('Dim_Product', conn, if_exists='replace', index=False)
dim_store.to_sql('Dim_Store', conn, if_exists='replace', index=False)
dim_date.to_sql('Dim_Date', conn, if_exists='replace', index=False)

# Load Fact Table
fact_sales.to_sql('Fact_Sales', conn, if_exists='replace', index=False)

print("Data Warehouse created successfully!")

# Check tables inside the database
tables = pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

display(tables)

Data Warehouse created successfully!

           name
0  Dim_Customer
1   Dim_Product
2     Dim_Store
3      Dim_Date
4    Fact_Sales

In [8]:
# Step 8A: Prepare Customer Dimension for SCD Type 2

dim_customer_scd = dim_customer.copy()

dim_customer_scd['Effective_Start_Date'] = pd.to_datetime('2026-07-01')
dim_customer_scd['Effective_End_Date'] = pd.to_datetime('9999-12-31', errors='coerce')
dim_customer_scd['Is_Current'] = 1

print("CUSTOMER DIMENSION - FIRST PIPELINE EXECUTION")
display(dim_customer_scd)

CUSTOMER DIMENSION - FIRST PIPELINE EXECUTION

,Customer_SK,Customer_ID,Customer_Name,City,Effective_Start_Date,Effective_End_Date,Is_Current
0,1,C001,Kamal,Colombo,2026-07-01,NaT,1
1,2,C002,Nimali,Kandy,2026-07-01,NaT,1
2,3,C003,Saman,Galle,2026-07-01,NaT,1
3,4,C004,Amali,Kurunegala,2026-07-01,NaT,1
4,5,C005,Nuwan,Colombo,2026-07-01,NaT,1

In [9]:
# Step 8B: Second Pipeline Execution - SCD Type 2

change_date = pd.Timestamp('2026-08-13')

# Close Kamal's old record
old_record = (
    (dim_customer_scd['Customer_ID'] == 'C001') &
    (dim_customer_scd['Is_Current'] == 1)
)

dim_customer_scd.loc[old_record, 'Effective_End_Date'] = change_date
dim_customer_scd.loc[old_record, 'Is_Current'] = 0

# Create new historical version
new_customer_version = pd.DataFrame({
    'Customer_SK': [dim_customer_scd['Customer_SK'].max() + 1],
    'Customer_ID': ['C001'],
    'Customer_Name': ['Kamal'],
    'City': ['Kandy'],
    'Effective_Start_Date': [change_date],
    'Effective_End_Date': [pd.NaT],
    'Is_Current': [1]
})

dim_customer_scd = pd.concat(
    [dim_customer_scd, new_customer_version],
    ignore_index=True
)

print("SCD TYPE 2 - SECOND PIPELINE EXECUTION")
display(
    dim_customer_scd[
        dim_customer_scd['Customer_ID'] == 'C001'
    ]
)

SCD TYPE 2 - SECOND PIPELINE EXECUTION

,Customer_SK,Customer_ID,Customer_Name,City,Effective_Start_Date,Effective_End_Date,Is_Current
0,1,C001,Kamal,Colombo,2026-07-01,2026-08-13,0
5,6,C001,Kamal,Kandy,2026-08-13,NaT,1

In [10]:
# Step 9: Analytical Query - Sales by Product

product_sales = staging_sales.groupby(
    'Product_Name'
).agg(
    Total_Quantity=('Quantity', 'sum'),
    Total_Gross_Sales=('Gross_Sales', 'sum'),
    Total_Discount=('Discount', 'sum'),
    Total_Net_Sales=('Net_Sales', 'sum')
).reset_index()

product_sales = product_sales.sort_values(
    'Total_Net_Sales',
    ascending=False
)

print("SALES PERFORMANCE BY PRODUCT")
display(product_sales)

SALES PERFORMANCE BY PRODUCT

,Product_Name,Total_Quantity,Total_Gross_Sales,Total_Discount,Total_Net_Sales
1,Laptop,3,750000,35000,715000
2,Monitor,2,130000,8000,122000
3,Mouse,9,31500,2000,29500
0,Keyboard,3,22500,1000,21500

In [11]:
# Step 10: Store Sales Analysis

store_sales = staging_sales.groupby(
    'Store_ID'
).agg(
    Number_of_Transactions=('Transaction_ID', 'count'),
    Total_Quantity=('Quantity', 'sum'),
    Total_Gross_Sales=('Gross_Sales', 'sum'),
    Total_Net_Sales=('Net_Sales', 'sum')
).reset_index()

store_sales = store_sales.merge(
    dim_store[['Store_ID', 'Store_Name']],
    on='Store_ID',
    how='left'
)

store_sales = store_sales[
    ['Store_ID', 'Store_Name', 'Number_of_Transactions',
     'Total_Quantity', 'Total_Gross_Sales', 'Total_Net_Sales']
]

print("SALES PERFORMANCE BY STORE")
display(store_sales)

SALES PERFORMANCE BY STORE

,Store_ID,Store_Name,Number_of_Transactions,Total_Quantity,Total_Gross_Sales,Total_Net_Sales
0,S001,Colombo Store,5,8,397500,378500
1,S002,Kandy Store,5,9,536500,509500

In [12]:
# Step 11: Customer Sales Analysis

customer_sales = staging_sales.groupby(
    ['Customer_ID', 'Customer_Name']
).agg(
    Number_of_Purchases=('Transaction_ID', 'count'),
    Total_Quantity=('Quantity', 'sum'),
    Total_Net_Sales=('Net_Sales', 'sum')
).reset_index()

customer_sales = customer_sales.sort_values(
    'Total_Net_Sales',
    ascending=False
)

print("CUSTOMER SALES ANALYSIS")
display(customer_sales)

CUSTOMER SALES ANALYSIS

,Customer_ID,Customer_Name,Number_of_Purchases,Total_Quantity,Total_Net_Sales
3,C004,Amali,2,2,297000
0,C001,Kamal,2,4,250000
2,C003,Saman,2,2,247500
4,C005,Nuwan,2,5,73000
1,C002,Nimali,2,4,20500

In [13]:
# Step 12: Create Second Source Data State

second_run_data = pd.DataFrame({
    'Transaction_ID': ['T011', 'T012', 'T013'],
    'Date': ['2026-08-13', '2026-08-14', '2026-08-15'],

    'Customer_ID': ['C001', 'C006', 'C002'],
    'Customer_Name': ['Kamal', 'Dilani', 'Nimali'],
    'City': ['Kandy', 'Gampaha', 'Kandy'],

    'Product_ID': ['P001', 'P004', 'P002'],
    'Product_Name': ['Laptop', 'Monitor', 'Mouse'],
    'Category': ['Electronics', 'Electronics', 'Accessories'],

    'Store_ID': ['S002', 'S001', 'S002'],

    'Quantity': [1, 1, 2],
    'Unit_Price': [250000, 65000, 3500],
    'Discount': [12000, 4000, 500]
})

second_run_data['Date'] = pd.to_datetime(second_run_data['Date'])

second_run_data['Gross_Sales'] = (
    second_run_data['Quantity'] * second_run_data['Unit_Price']
)

second_run_data['Net_Sales'] = (
    second_run_data['Gross_Sales'] - second_run_data['Discount']
)

print("SECOND SOURCE DATA STATE")
display(second_run_data)

SECOND SOURCE DATA STATE

,Transaction_ID,Date,Customer_ID,Customer_Name,City,Product_ID,Product_Name,Category,Store_ID,Quantity,Unit_Price,Discount,Gross_Sales,Net_Sales
0,T011,2026-08-13,C001,Kamal,Kandy,P001,Laptop,Electronics,S002,1,250000,12000,250000,238000
1,T012,2026-08-14,C006,Dilani,Gampaha,P004,Monitor,Electronics,S001,1,65000,4000,65000,61000
2,T013,2026-08-15,C002,Nimali,Kandy,P002,Mouse,Accessories,S002,2,3500,500,7000,6500

In [14]:
# Step 13: Process Second Pipeline Execution

# Add new customer Dilani to SCD Customer Dimension
new_customer = pd.DataFrame({
    'Customer_SK': [dim_customer_scd['Customer_SK'].max() + 1],
    'Customer_ID': ['C006'],
    'Customer_Name': ['Dilani'],
    'City': ['Gampaha'],
    'Effective_Start_Date': [pd.Timestamp('2026-08-14')],
    'Effective_End_Date': [pd.NaT],
    'Is_Current': [1]
})

dim_customer_scd = pd.concat(
    [dim_customer_scd, new_customer],
    ignore_index=True
)

# Get CURRENT customer surrogate keys
current_customers = dim_customer_scd[
    dim_customer_scd['Is_Current'] == 1
][['Customer_SK', 'Customer_ID']]

# Prepare second-run fact records
second_fact = second_run_data.merge(
    current_customers,
    on='Customer_ID',
    how='left'
)

second_fact = second_fact.merge(
    dim_product[['Product_SK', 'Product_ID']],
    on='Product_ID',
    how='left'
)

second_fact = second_fact.merge(
    dim_store[['Store_SK', 'Store_ID']],
    on='Store_ID',
    how='left'
)

print("SECOND PIPELINE - CUSTOMER DIMENSION")
display(dim_customer_scd)

print("\nSECOND PIPELINE - NEW FACT RECORDS")
display(
    second_fact[
        ['Transaction_ID', 'Customer_SK', 'Product_SK',
         'Store_SK', 'Quantity', 'Gross_Sales', 'Net_Sales']
    ]
)

SECOND PIPELINE - CUSTOMER DIMENSION

,Customer_SK,Customer_ID,Customer_Name,City,Effective_Start_Date,Effective_End_Date,Is_Current
0,1,C001,Kamal,Colombo,2026-07-01,2026-08-13,0
1,2,C002,Nimali,Kandy,2026-07-01,NaT,1
2,3,C003,Saman,Galle,2026-07-01,NaT,1
3,4,C004,Amali,Kurunegala,2026-07-01,NaT,1
4,5,C005,Nuwan,Colombo,2026-07-01,NaT,1
5,6,C001,Kamal,Kandy,2026-08-13,NaT,1
6,7,C006,Dilani,Gampaha,2026-08-14,NaT,1

SECOND PIPELINE - NEW FACT RECORDS

,Transaction_ID,Customer_SK,Product_SK,Store_SK,Quantity,Gross_Sales,Net_Sales
0,T011,6,1,2,1,250000,238000
1,T012,7,4,1,1,65000,61000
2,T013,2,2,2,2,7000,6500

In [15]:
# Step 14: Update Fact Table After Second Pipeline Execution

# Add simple Date_SK values for the new August dates
second_fact['Date_SK'] = [11, 12, 13]

second_fact_final = second_fact[
    [
        'Transaction_ID',
        'Date_SK',
        'Customer_SK',
        'Product_SK',
        'Store_SK',
        'Quantity',
        'Unit_Price',
        'Discount',
        'Gross_Sales',
        'Net_Sales'
    ]
]

# Combine first and second pipeline fact data
updated_fact_sales = pd.concat(
    [fact_sales, second_fact_final],
    ignore_index=True
)

print("UPDATED FACT SALES TABLE AFTER SECOND PIPELINE EXECUTION")
display(updated_fact_sales)

UPDATED FACT SALES TABLE AFTER SECOND PIPELINE EXECUTION

,Transaction_ID,Date_SK,Customer_SK,Product_SK,Store_SK,Quantity,Unit_Price,Discount,Gross_Sales,Net_Sales
0,T001,1,1,1,1,1,250000,10000,250000,240000
1,T002,2,2,2,1,2,3500,500,7000,6500
2,T003,3,3,3,2,1,7500,0,7500,7500
3,T004,4,1,2,1,3,3500,500,10500,10000
4,T005,5,4,1,2,1,250000,15000,250000,235000
5,T006,6,5,4,1,1,65000,5000,65000,60000
6,T007,7,2,3,2,2,7500,1000,15000,14000
7,T008,8,3,1,2,1,250000,10000,250000,240000
8,T009,9,4,4,1,1,65000,3000,65000,62000
9,T010,10,5,2,2,4,3500,1000,14000,13000
10,T011,11,6,1,2,1,250000,12000,250000,238000
11,T012,12,7,4,1,1,65000,4000,65000,61000
12,T013,13,2,2,2,2,3500,500,7000,6500

In [16]:
# Step 15: Final Data Warehouse Validation

print("========== FINAL DATA WAREHOUSE VALIDATION ==========")

print("\nTotal Fact Records:")
print(len(updated_fact_sales))

print("\nTotal Customer Dimension Records:")
print(len(dim_customer_scd))

print("\nCurrent Customers:")
print(len(dim_customer_scd[dim_customer_scd['Is_Current'] == 1]))

print("\nHistorical Customer Records:")
print(len(dim_customer_scd[dim_customer_scd['Is_Current'] == 0]))

print("\nTotal Net Sales:")
print(updated_fact_sales['Net_Sales'].sum())

print("\nDuplicate Transaction IDs:")
print(updated_fact_sales['Transaction_ID'].duplicated().sum())

print("\nMissing Customer Keys:")
print(updated_fact_sales['Customer_SK'].isnull().sum())

print("\nVALIDATION COMPLETED SUCCESSFULLY")

========== FINAL DATA WAREHOUSE VALIDATION ==========

Total Fact Records:
13

Total Customer Dimension Records:
7

Current Customers:
6

Historical Customer Records:
1

Total Net Sales:
1193500

Duplicate Transaction IDs:
0

Missing Customer Keys:
0

VALIDATION COMPLETED SUCCESSFULLY